# Generated by Django 5.0 on 2025-08-01 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='面试官姓名')),
                ('interviewer_id', models.CharField(max_length=20, unique=True, verbose_name='面试官学号')),
                ('password', models.CharField(max_length=128, verbose_name='面试官密码')),
                ('department_team', models.CharField(choices=[('公关部-IT组', '公关部-IT组'), ('公关部-活动组', '公关部-活动组'), ('新媒体部-设计组', '新媒体部-设计组'), ('新媒体部-运营组', '新媒体部-运营组'), ('商业部', '商业部'), ('产品研发部', '产品研发部'), ('策划部', '策划部')], max_length=50, verbose_name='面试官部门小组')),
                ('resumes_to_screen', models.JSONField(default=list, verbose_name='待筛选简历')),
                ('interviews_pending', models.IntegerField(default=0, verbose_name='待面试数')),
                ('available_time_slots', models.JSONField(default=dict, verbose_name='可用面试时间及人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '面试官',
                'verbose_name_plural': '面试官',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('first_choice', models.CharField(choices=[('公关部', '公关部'), ('新媒体部', '新媒体部'), ('商业部', '商业部'), ('产品研发部', '产品研发部'), ('策划部', '策划部')], max_length=50, verbose_name='第一志愿部门')),
                ('second_choice', models.CharField(choices=[('公关部', '公关部'), ('新媒体部', '新媒体部'), ('商业部', '商业部'), ('产品研发部', '产品研发部'), ('策划部', '策划部')], max_length=50, verbose_name='第二志愿部门')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='上传的简历pdf')),
                ('first_interview_time', models.DateTimeField(blank=True, null=True, verbose_name='第一志愿面试时间')),
                ('second_interview_time', models.DateTimeField(blank=True, null=True, verbose_name='第二志愿面试时间')),
                ('resume_result', models.CharField(blank=True, choices=[('通过', '通过'), ('未通过', '未通过')], max_length=20, null=True, verbose_name='简历筛选结果')),
                ('first_interview_status', models.CharField(choices=[('未安排', '未安排'), ('已安排', '已安排'), ('已完成', '已完成')], default='未安排', max_length=20, verbose_name='第一志愿面试状态')),
                ('second_interview_status', models.CharField(choices=[('未安排', '未安排'), ('已安排', '已安排'), ('已完成', '已完成')], default='未安排', max_length=20, verbose_name='第二志愿面试状态')),
                ('first_interview_result', models.CharField(blank=True, choices=[('通过', '通过'), ('未通过', '未通过')], max_length=20, null=True, verbose_name='第一志愿面试结果')),
                ('second_interview_result', models.CharField(blank=True, choices=[('通过', '通过'), ('未通过', '未通过')], max_length=20, null=True, verbose_name='第二志愿面试结果')),
                ('admission_result', models.CharField(blank=True, choices=[('录取', '录取'), ('未录取', '未录取')], max_length=20, null=True, verbose_name='录取结果')),
                ('admission_department', models.CharField(blank=True, choices=[('公关部', '公关部'), ('新媒体部', '新媒体部'), ('商业部', '商业部'), ('产品研发部', '产品研发部'), ('策划部', '策划部')], max_length=50, null=True, verbose_name='录取部门')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('first_interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_applicants', to='homepage.interviewer', verbose_name='第一志愿面试官')),
                ('second_interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_applicants', to='homepage.interviewer', verbose_name='第二志愿面试官')),
            ],
            options={
                'verbose_name': '新生申请表',
                'verbose_name_plural': '新生申请表',
            },
        ),
    ]
