# Generated by Django 5.0 on 2025-08-01 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': '新生申请', 'verbose_name_plural': '新生申请'},
        ),
        migrations.RenameField(
            model_name='interviewer',
            old_name='interviewer_id',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='admission_department',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='resume_result',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='available_time_slots',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='interviews_pending',
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_screening_result',
            field=models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '未通过'), ('not_scheduled', '未安排'), ('scheduled', '已安排'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='简历筛选结果'),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='available_interview_times',
            field=models.JSONField(default=dict, verbose_name='可用的面试时间及最大人数'),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='pending_interviews',
            field=models.IntegerField(default=0, verbose_name='待面试数'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='admission_result',
            field=models.BooleanField(default=False, verbose_name='录取结果'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, default='待反馈', verbose_name='反馈意见'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_interview_result',
            field=models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '未通过'), ('not_scheduled', '未安排'), ('scheduled', '已安排'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第一志愿面试结果'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_interview_status',
            field=models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '未通过'), ('not_scheduled', '未安排'), ('scheduled', '已安排'), ('completed', '已完成')], default='not_scheduled', max_length=20, verbose_name='第一志愿面试状态'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_interviews', to='homepage.interviewer', verbose_name='第一志愿面试官'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='grade',
            field=models.CharField(choices=[('freshman', '大一'), ('sophomore', '大二'), ('junior', '大三'), ('senior', '大四'), ('graduate', '研究生')], max_length=20, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='resumes/%Y/%m/%d/', verbose_name='上传的简历PDF'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='second_interview_result',
            field=models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '未通过'), ('not_scheduled', '未安排'), ('scheduled', '已安排'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第二志愿面试结果'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='second_interview_status',
            field=models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '未通过'), ('not_scheduled', '未安排'), ('scheduled', '已安排'), ('completed', '已完成')], default='not_scheduled', max_length=20, verbose_name='第二志愿面试状态'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='second_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_interviews', to='homepage.interviewer', verbose_name='第二志愿面试官'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='admitted_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_applicants', to='homepage.department', verbose_name='录取部门'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_applicants', to='homepage.department', verbose_name='第一志愿部门'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_applicants', to='homepage.department', verbose_name='第二志愿部门'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='department_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='homepage.department', verbose_name='面试官部门小组'),
        ),
    ]
